language: node_js
node_js:
  - "11.3.0"

jobs:
  include:
  - stage: build image
    services:
    - docker
    before_script:
    - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
    script:
    - docker build -t bombergame/frontend .
    after_success:
    - if [ ${TRAVIS_BRANCH} = "master" ]; then
        docker push bombergame/frontend;
      fi
  - stage: deploy
    before_script:
      - curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
    script:
    - if [ ${TRAVIS_BRANCH} = "master" && ${TRAVIS_PULL_REQUEST} = false ] ; then
        sh trigger-travis.sh bombergame service-config ${TRAVIS_ACCESS_TOKEN};
      fi
